add python-venv to dependencies
Error logs:

 > Running task 1 of 1: invoke develop

0.15.4.0
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/ubuntu/.local/pipx/shared/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

'/usr/bin/python3 -m venv --clear /home/ubuntu/.local/pipx/shared' failed
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/usr/local/bin/copier", line 11, in <module>
    sys.exit(CopierApp.run())
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.6/dist-packages/copier/cli.py", line 17, in _wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/copier/cli.py", line 158, in main
    self.parent._copy(template_src, destination_path)
  File "/usr/local/lib/python3.6/dist-packages/copier/cli.py", line 121, in _copy
    **kwargs,
  File "/usr/local/lib/python3.6/dist-packages/copier/main.py", line 142, in copy
    copy_local(conf=conf)
  File "/usr/local/lib/python3.6/dist-packages/copier/main.py", line 196, in copy_local
    conf, render, [{"task": t, "extra_env": {"STAGE": "task"}} for t in conf.tasks]
  File "/usr/local/lib/python3.6/dist-packages/copier/main.py", line 369, in run_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'invoke develop' returned non-zero exit status 1.